route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - receiver: slack-notifications
    match:
      severity: warning
  - receiver: slack-notifications
    match:
      severity: critical

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
- name: 'slack-notifications'
  slack_configs:
  - channel: "#alerts"
    send_resolved: true
    api_url: "https://hooks.slack.com/services/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"
    title: "{{ .CommonLabels.alertname }}"
    text: |
      *Alert:* {{ .CommonLabels.alertname }}
      *Summary:* {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
      *Description:* {{ range .Alerts }}{{ .Annotations.description }}{{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'info'
    equal: ['alertname', 'dev', 'instance']
