groups:
  - name: systemd-alerts
    rules:
      - alert: NginxServiceDown
        expr: node_systemd_unit_state{name="nginx.service", state="active"} == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "Nginx service is down"
          description: "The Nginx systemd service has been inactive for more than 2 minutes."
