apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://localhost:9090
    isDefault: true
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin

  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100  # Replace with the URL of your Loki instance
    jsonData:
      maxLines: 1000
